const body = document.body;
const mainContainer = document.createElement('div');
const mainParagraph = document.createElement('p');
mainParagraph.style.color = 'rgb(255,0,0)';
mainParagraph.textContent = "Hey, I'm red!";
const mainHeader = document.createElement('h3');
mainHeader.style.color = 'rgb(0,0,255)';
mainHeader.textContent = "I'm a blue h3!";
const subContainer = document.createElement('div');
subContainer.style.border = '3px solid rgb(0, 0, 0)';
subContainer.style.borderColor = '';
subContainer.style.backgroundColor = 'rgb(255,150,150)';
const subHeader = document.createElement('h1');
subHeader.textContent = "I'm in a div";
const subParagraph = document.createElement('p');
subParagraph.textContent = "ME TOO!";
subContainer.appendChild(subHeader);
subContainer.appendChild(subParagraph);
mainContainer.appendChild(mainParagraph);
mainContainer.appendChild(mainHeader);
mainContainer.appendChild(subContainer);
body.appendChild(mainContainer);